stages:
  - test

verify-php7.4:
  image: grifart/php7.4-with-gulp-and-all-php-modules
  stage: test
  interruptible: true

  script:
    - composer install
    - composer run verify

verify-php8.0:
  image: grifart/php8.0-with-all-modules-and-various-tools
  stage: test
  interruptible: true

  script:
    - composer install
    - composer run verify


verify-php8.1:
  image: grifart/php8.1-with-all-modules-and-various-tools
  stage: test
  interruptible: true

  script:
    - composer install
    - composer run verify
